AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'test/**/*'

Naming/PredicateName:
  AllowedMethods:
    - has_many
