AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Max: 65
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'db/schema.rb'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Max: 30
  Exclude:
    - 'test/**/*'

Naming/PredicateName:
  AllowedMethods:
    - has_many
