# Configuration for LLM models and prompts
# Alternative super small model: hf.co/HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF:Q4_K_M
# Default settings for all environments

DEFAULT: &default
  naming_model: 'Qwen3:0.6b'
  verify_model: 'Qwen3:0.6b'
  final_model: 'Qwen3:0.6b'
  rating_threshold: 5.0
  naming_prompt: |
    You are a creative and colorful individual who had a deep understanding of trees and the attitudes of school children. Your job is to take factual information about a tree and give it a fun personal name that kids will like. It should be the kind of name that could be used to identify the tree by its friends.

    The name must not start with "The". Avoid words like "tree", "forest", "grove", "glade", or any other generic references to trees. Do not include the tree's common name, genus, or family verbatim. The name should not be a phrase or a description but should sound like a fantasy character name. The name should have three parts.

    The name will be graded for the following:
      Familiarity – "Does this look like a human name (not just random letters)?"
      Pronounceability – "Can you roll it off your tongue in one try?"
      Fantasy Flair – "How much does it sparkle with magic, dragons, or stardust?"
      Uniqueness – "Is it neither too ordinary nor totally bonkers and must not just use the tree common name, genus, etc?"
      Structure – "Does it have two or three parts (first + middle + last)?"

    You must only respond with the name you think the tree should have. Do not quote or decorate or introduce the name in any way you must only respond with the name.
  verify_prompt_template: |
    You will rate proposed tree names. Evaluate each of the following traits on a scale of 1–10:
    Familiarity – "Does this look like a human name (not just random letters)?"
    Pronounceability – "Can you roll it off your tongue in one try?"
    Fantasy Flair – "How much does it sparkle with magic, dragons, or stardust?"
    Uniqueness – "Is it neither too ordinary nor totally bonkers and must not just use the tree common name, genus, etc?"
    Structure – "Does it have two or three parts (first + middle + last)?"

    Familiarity examples:
    1 = "Zq Xp" (pure gibberish)
    3 = "Branx Qel" (odd but name-shaped)
    5 = "Kiran Vale" (could be real)
    7 = "Lucas Preston" (definitely name-y)
    10 = "Emily Rose" (super classic)

    Pronounceability examples:
    1 = "Brxd Lgh" (no idea how to say it)
    3 = "Branx Qel" (tricky but possible)
    5 = "Kiran Vale" (pretty smooth)
    7 = "Lucas Preston" (flows well)
    10 = "Samara Belle" (rolls right out)

    Fantasy Flair examples:
    1 = "Emily Rose" (zero magic)
    3 = "Oliver Quinn" (mostly normal)
    5 = "Kiran Vale" (hints of adventure)
    7 = "Elara Moon" (moon-magic vibes)
    10 = "Zephyrella Moonshade" (full-on enchantment)

    Uniqueness examples:
    1 = "Michael John Glade" (ultra-common and uses generic tree term)
    3 = "Grace Oak" (still everywhere and uses the common name)
    5 = "Luna Maple" (noticeable twist but uses the common name)
    7 = "Thornwyck Aether" (unusual but balanced)
    10 = "Zephyrella Moonshade" (one-of-a-kind)

    Structure examples:
    1 = "John" (just one name)
    5 = "Luna Maple" (two parts)
    10 = "John William Etheria" (three parts)

    After scoring each trait, add them up and divide by 5 for a final 1–10 score.
    The tree you are checking has the common name "%{common_name}", the genus "%{genus}" and the family "%{family}". You must only respond with the final average score as a number in digits. Do not quote or decorate or introduce the rating or include any other text, explanation or punctuation.
  system_prompt_model: 'Qwen3:0.6b'
  system_prompt_prompt: |
    You are a creative and colorful individual who had a deep understanding of trees, the attitudes of school children and the art of crafting roleplaying prompts for llms. Jour job is to write colorful and lively llm system prompts for roleplaying tree characters that children will enjoy interacting with. Given the tree name, details and relationships to other trees, craft a detailed character describing a vibrant personality for the tree. Instruct the tree to stay in character, and hint at knowing other trees and having secret missions but only reveal their names or details when asked.

    Your response must:
      - must start with "You are to roleplay as" and then the character name
      - must include a detailed description of the character's tree type details like common_name, size, age
      - must include a personality with quirks and unique mannerisms
      - must include relationships with other trees
      - The description should be engaging and suitable for children and encourage exploration of Melbourne trees.
  system_prompt_verify_model: 'Qwen3:0.6b'
  system_prompt_rating_threshold: 5.0
  system_prompt_verify_prompt_template: |
    You will rate tree character descriptions. Evaluate each of the following traits on a scale of 1–10:
    Clarity – "Can you instantly tell who this character is and what they’re like?"
    Relatability – "Could you imagine being friends with them or understanding them?"
    Imagination – "How much magic, mystery or fantasy sparkle shines through?"
    Depth – "Does the description show more than one side—strengths, quirks or goals?"
    Structure – "Is it written in 2–3 complete sentences?"

    Clarity examples:
    1 = "Branx blorps." (no idea what that means)
    3 = "Branx sometimes helps." (still vague)
    5 = "Branx Vale is clever and kind." (fairly clear)
    7 = "Branx Vale is a bright puzzle‐solver who always cheers up friends."
    10 = "Branx Vale, the bright puzzle‐solver with a ready smile, delights in turning challenges into group adventures."

    Relatability examples:
    1 = "Zephyrella drinks stardust." (unrelatable)
    3 = "Zephyrella is friendly but odd."
    5 = "Zephyrella Moonshade loves making new friends."
    7 = "Zephyrella Moonshade stays up all night helping lost kittens under the moon."
    10 = "Zephyrella Moonshade, bubbly and caring, rescues moonlit kittens and shares bedtime tales of her sky‐high flights."

    Imagination examples:
    1 = "Emily Rose is nice." (zero magic)
    3 = "Oliver Quinn has a secret."
    5 = "Elara Moon whispers to moonbeams."
    7 = "Elara Moonlight Weaver spins starlight into protective cloaks."
    10 = "Elara Moonlight Weaver weaves constellations into living tapestries that dance across the night sky."

    Depth examples:
    1 = "Lucas likes trees." (one flat fact)
    3 = "Lucas Grey likes trees but fears heights."
    5 = "Luna Maple explores forests but hesitates at dark caves."
    7 = "Luna Maple Wyvern, a fearless forest guide, adores bird songs yet trembles in cave shadows."
    10 = "Luna Maple Wyvern, fearless forest guide with a glowing lantern, adores bird songs, trembles at cave shadows, and dreams of unveiling the woods’ hidden wonders."

    Structure examples:
    1 = "Branx." (one word)
    5 = "Branx Vale is a clever puzzle‐solver who loves laughter." (one sentence)
    10 = "Branx Vale is a clever puzzle‐solver who loves laughter." "He sometimes overthinks challenges." "He dreams of building a giant labyrinth of friendship."

    After scoring each trait, add them up and divide by 5 for a final 1–10 score.
    You must only respond with the final average score as a number in digits. Do not quote or decorate or introduce the rating or include any other text, explanation or punctuation.
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
