name: CI

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec ruby test/run_tests.rb | tee test_output.txt
      - name: Run Brakeman
        run: |
          bundle exec brakeman -q | tee brakeman_report.txt
      - name: Run RuboCop
        run: |
          bundle exec rubocop --format simple --no-color | tee rubocop_report.txt
        continue-on-error: true
      - name: Run bundler-audit
        run: |
          bundle exec bundler-audit check --update | tee bundler_audit_report.txt
        continue-on-error: true
      - name: Show reports
        run: |
          echo '### RuboCop'
          if [ -f rubocop_report.txt ]; then cat rubocop_report.txt; else echo "rubocop_report.txt not found"; fi
          echo '### bundler-audit'
          if [ -f bundler_audit_report.txt ]; then cat bundler_audit_report.txt; else echo "bundler_audit_report.txt not found"; fi
          echo '### Brakeman'
          if [ -f brakeman_report.txt ]; then cat brakeman_report.txt; else echo "brakeman_report.txt not found"; fi
          echo '### Coverage'
          if [ -f coverage.txt ]; then cat coverage.txt; else echo "coverage.txt not found"; fi
      - name: Comment summary
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('test_output.txt','utf8').trim().split('\n').pop();
            const coverage = fs.readFileSync('coverage.txt','utf8').trim().split('\n').pop();
            const body = `**Test Summary**\n\n\`${summary}\`\n\n**Coverage**\n\n\`${coverage}\``;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

      - name: Comment RuboCop report
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('rubocop_report.txt','utf8');
            const body = `**RuboCop Report**\n\n\`\`\`\n${report}\n\`\`\``;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

      - name: Comment bundler-audit report
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('bundler_audit_report.txt','utf8');
            const body = `**bundler-audit Report**\n\n\`\`\`\n${report}\n\`\`\``;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

      - name: Comment Brakeman report
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('brakeman_report.txt','utf8');
            const body = `**Brakeman Report**\n\n\`\`\`\n${report}\n\`\`\``;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

